### ISSUE TITLE
Build a system to automatically generate and integrate files with Protocol Buffers.

### ISSUE THREAD

**Issue by Hirochon** [mocoog/epics#3]
## Todo

- [x] You can use aggregation-pb to hook the merge of a PR, and package-repo to get the title of the PR.
- [x] Check the process of not running compile when the PR is closed without merging.
- [x] Obtain the characters to the left of the colon in "gateway:hogehoge" from the PR title.
- [x] Write a test

**Comment by Hirochon** [comment]
Complete！！！
